### ISSUE TITLE
KeystoneManager Errors

### ISSUE THREAD

**Issue by kaseyd24** [kaminaris/KeystoneManager#5] opened 2018-11-12 22:35 UTC
Date: 2018-11-12 17:28:22
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\KeystoneManager\main.lua line 425:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   (tail call): ?
   (tail call): ?
   (tail call): ?
   [C]: pairs()
   KeystoneManager\main.lua:425: ?()
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  ACP, vr259 
  Altoholic, vr190
  AngryAssignments, vv1.11.2
  AngryKeystones, v
  AngryWorldQuests, v
  ArkInventory, v30815
  ArkInventoryRules, v10200
  ArkInventorySearch, v10200
  AskMrRobot, v67
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  AutoRepair, v
  AzeritePowerWeights, v8.0.29
  AzeriteTooltip, v1.82
  BadBoy, vv8.0.14
  BadBoyCCleaner, vv8.0.0
  BattlePetBreedID, vr179
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BlockChinese, vv1.6
  BrokerBattleRes, v1.2
  ClassOrderHallsComplete, v1.33
  Clique, vv80000-1.0.0
  CollectMe, v2.10.1
  CrapAway, v
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v8.0.15
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DBMVPVEM, v8.0.5
  Decursive, v2.7.6.1
  Details, v
  DetailsDeathGraphs, v
  DetailsDmgRank, v
  DetailsDpsTuning, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTimeAttack, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v8.0.6158 (SwimmingSeadragon)
  FishingBuddy, v1.9.21
  GarrisonCommanderBroker, v3.0.0 1.1.0
  GatherMate2, v1.43.4
  Grail, v098
  GrailQuestsenUS, v27178
  Grid, v8.0.1.1
  GTFO, v4.46.9
  GuildRecr, v3.4
  IskarAssist, v
  KeystoneHelper, v8.0.0.1
  KeystoneManager, v8.0.2
  LibSharedMedia30, v3.0-104
  MasterPlanA, vA
  MaxDps, v8.0.10.2
  MinimapButtonFrame, v3.1.10h
  MinimapButtonFrameSkinPack, v3.0.1b
  MonkeySpeed, vv3.3.13
  MPH, v1.4
  MythicPlusLoot, v2.3
  MythicPlusTimer, v2.4
  NPCScan, v8.0.1.13
  Oilvl, v8.0.2
  Omen, v3.2.0
  Overachiever, v1.0.4
  OverachieverCache, v1.0.4
  OverachieverTrade, v1.0.4
  Pawn, v2.2.31
  PersonalLootHelper, v2.17
  Postal, vv3.6.0
  Prat30, vr1193      
  Prat30Libraries, v
  PremadeGroupsFilter, v1.22
  RaidAssist, v
  RaiderIO, v8.0.1 (v201811121910)
  RaiderIODBUSA, v
  RaiderIODBUSAR, v
  RaiderIODBUSH, v
  RaiderIODBUSHR, v
  Rarity, v1.0 (r681-release)
  RarityOptions, v
  ReputationSorter, v
  RSA, vr510-Release
  RSADruid, v
  SavedInstances, v8.0.6
  ServerHop, v8.0.1.1
  SexyMap, vv8.0.8
  Simulationcraft, v1.10.7
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  Spy, v3.5.13
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20181110
  TidyPlates, v6.19.2
  TidyPlatesGraphite, v
  TidyPlatesGrey, v
  TidyPlatesNeon, v
  TidyPlatesQuatre, v
  TidyPlatesHub, v
  TidyPlatesWidgets, v
  TipTac, v18.08.20
  TipTacItemRef, v18.08.12
  TipTacTalents, v18.07.30
  Titan, v5.14.12.80000
  TitanBag, v5.14.12.80000
  TitanChallengeModes, v0.3.1
  TitanClock, v5.14.12.80000
  TitanCurrency, v8.0.B
  TitanGold, v5.14.12.80000
  TitanGuild, v8.0.0.0
  TitanLocation, v5.14.12.80000
  TitanLootType, v5.14.12.80000
  TitanPerformance, v5.14.12.80000
  TitanRepair, v5.14.12.80000
  TitanSocial, v8.0.1
  TitanVolume, v5.14.12.80000
  TitanXP, v5.14.12.80000
  TomTom, vv80001-1.0.2
  TradeSkillMaster, vv4.5.2
  TradeSkillMasterAppHelper, vv4.0
  WeakAuras, v2.9.1
  WorldQuestsList, v81
  WorldQuestTracker, v
  WowPro, v8.0.1L
  WoWProAchievements, v8.0.1L
  WoWProDailies, v8.0.1L
  WoWProLeveling, v8.0.1L
  WowProProfession, v8.0.1L
  WoWProWorldEvents, v8.0.1L
  ZPerl, v5.6.4
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=fd8)

**Comment by pwilkowski** [comment] 2018-11-14 12:32
Ok so how did you manage to get this error? I need some way to reproduce the issue.

**Comment by kaseyd24** [comment] 2018-11-14 16:42
Logging on.  That is it.

**Comment by pwilkowski** [comment] 2018-11-15 02:16
Wait a moment, do you have version from curse or from github?
Have you tried disabling other addons? Does it still happen with JUST keystoneManager?

**Comment by kaseyd24** [comment] 2018-11-15 07:59
Curse... only KeystoneManager.. I tried disabling other addons.  Still creates error on logon

**Comment by pwilkowski** [comment] 2018-11-16 12:02
So just to be sure, you are getting error but addon is working? Or not?
The worst thing about this bug is that I cannot reproduce it...

It is happening when iterating over map names. I will try to fix it today.

**Comment by kaseyd24** [comment] 2018-11-16 19:24
It happens only when I log in, I can send a screen shot if it helps.  I would like to give you as much information as I can to help you..  It seems to be working fine.   I know its low down on the totem pole as far as needed fixes, just wanted to give you the LUA error.. I dont know if I'm an isolated incident or not. Any way I can help debug it more???

**Comment by pwilkowski** [comment] 2018-11-22 23:54
This should be fixed in 8.0.3

**Closed as completed by pwilkowski** 2018-11-22 23:54 UTC
